[tox]
requires =
    tox-uv>=1.25
    #
min_version = 4.22
env_list =
    py314
    py313
    py312
    py311
    lint
    #

[testenv]
package = skip
uv_resolution = lowest-direct
dependency_groups =
    dev
    #
commands =
    pytest {posargs}
    mypy
    #

[testenv:lint]
commands =
    ruff check .
    ruff format --check .
    #
